[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_AIRTABLE_BASE_ID"

[[redirects]]
  from = "/handheld.html"
  to = "/handheld.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
